### ISSUE TITLE
Add GroundView Logo to README.md

### ISSUE THREAD

**Issue by jchard** [GroundWorkRenewables/grndwork-api-client#15]
Please add the GroundView logo to the API README. Both .jpeg and .png versions are attached.

![GroundView](https://user-images.githubusercontent.com/7266242/151395564-54000ba1-f7a4-4ea8-84b4-66367e14cc90.png)
![GroundView](https://user-images.githubusercontent.com/7266242/151395568-eec56e4c-4ef2-47b3-aef2-74da62596631.jpg)

**Comment by ianmetcalf** [comment]
Done
